import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const navData = [
  {
    href: '/',
    title: "Upload Fonts"
  },
  {
    href: '/create_group',
    title: "Create Group"
  },
  {
    href: '/font_groups',
    title: "Font Groups"
  },
];
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Font App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full bg-gradient-to-r from-sky-600 to-indigo-600 h-20 shadow-lg">
          <ul className="flex items-center justify-center text-white text-lg font-semibold gap-8 h-full">
            {navData.map((item, index) => (
              <Link href={item.href} key={index}>
                <li className="hover:text-yellow-400 hover:scale-110 transition-transform duration-300 ease-in-out cursor-pointer">
                  {item.title}
                </li>
              </Link>
            ))}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
